server:
  port: 7001
  servlet:
    context-path: /ec-oms-admin

spring:
  application:
    name: ec-oms-admin
  security:
    user:
      name: linn
      password: linn

  cloud:
    nacos:
      discovery:
        namespace: 6f1143ce-9269-4a8b-9040-41b71ff0e86f
        enabled: true
        server-addr: localhost:8848
        metadata:
          user.name: linn
          user.password: linn

  thymeleaf:
    check-template: false
    check-template-location: false

management:
  server:
    port: 17001
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always