server:
  port: 7002
  servlet:
    context-path: /ec-oms-authorization-center # 访问端口号后面接口前面需要增加的路径

spring:
  application:
    name: ec-oms-authorization-center

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/ec-oms-cloud?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        show_sql: true
    show-sql: true

  cloud:
    nacos:
      discovery:
        namespace: fa4796a0-246b-4ce7-8391-4652dd8047ef
        enabled: true
        server-addr: localhost:8848
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always